before_script:
  - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
  - export NVM_DIR="$HOME/.nvm"
  - '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm'
  - |
    if ! command -v npm &> /dev/null; then
      nvm install 20  # Install Node.js version 20 (or your desired version)
    fi
  - nvm use 20  # Use Node.js version 20 (or your desired version)

cache:
  paths:
    - node_modules/

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - npm install
    - npm run build
    - mv build build-default
    - npm run build:vk
    - mv build build-vk
    - npm run build:tg
    - mv build build-tg
    - mv build-default build
    - mv build-vk ./build/vk
    - mv build-tg ./build/telegram

deploy-dev:
  stage: deploy
  script:
    - ssh root@$DEPLOY_SERVER_IP "rm -rf /var/www/beta.memesis.ru/$APP_DEPLOY_FOLDER_NAME"
    - rsync -aP build/* root@$DEPLOY_SERVER_IP:/var/www/beta.memesis.ru/$APP_DEPLOY_FOLDER_NAME
  variables:
    GIT_CHECKOUT: "false"
  only:
    - dev

deploy-master:
  stage: deploy
  script:
    - ssh root@$DEPLOY_SERVER_IP "rm -rf /var/www/memesis.ru/$APP_DEPLOY_FOLDER_NAME"
    - rsync -aP build/* root@$DEPLOY_SERVER_IP:/var/www/memesis.ru/$APP_DEPLOY_FOLDER_NAME
  variables:
    GIT_CHECKOUT: "false"
  only:
    - master

variables:
  CI: "false"
