export enum SCREENS {
    THE_START = "THE_START",
    THE_LOADING = "THE_LOADING",
    THE_COMICS = "THE_COMICS",
    THE_ONBOARDING = "THE_ONBOARDING",
    THE_GAME = "THE_GAME",
    THE_RESULT = "THE_RESULT",
    THE_SHARE = "THE_SHARE"
}